### ISSUE TITLE
Popup Bookmark Bar Feature

### ISSUE THREAD

**Issue by damian-ds7** [n7itro/Zen-Themes#1]
It would be great to add a popup bookmark bar to the Firefox CSS theme, similar to what was implemented in [firefox mod blur theme](https://github.com/datguypiko/Firefox-Mod-Blur). The feature would allow users to quickly access their bookmarks by hovering near url bar.

![popout bookmarks](https://github.com/user-attachments/assets/6529140c-7565-4b8c-b723-caa74f9d0843)

**Comment by n7itro** [comment]
@damian-ds7 This feature will be added when the update is reviewed. Let me know if it works properly and what improvements I should make!

**Comment by damian-ds7** [comment]
@n7itro everything seems to work fine, thanks again for implementing this function

**Comment by n7itro** [comment]
> @n7itro everything seems to work fine, thanks again for implementing this function

Do the animations work? If not, I'm pushing an update in a bit that should fix it

**Comment by n7itro** [comment]
@damian-ds7 thank you for the feedback. I will make the animation faster. You do still need to hover over the top toolbar to trigger the expand, hovering near it doesn't work which might make it feel slow.

Also, thanks for the fix. I have experienced that issue with the Github logo on the normal tab sidebar too, so this might be an issue with Zen. I will look into it.

**Comment by damian-ds7** [comment]
@n7itro I've also encountered this bug when bookmark toolbar is disabled

![image](https://github.com/user-attachments/assets/58294d0d-6641-4f6d-835d-af2b9c8e344a)

and browser needs to be restarted to use bookmark toolbar after enabling it otherwise it hides too early

[Screencast from 2024-08-20 21-04-54.webm](https://github.com/user-attachments/assets/e722f838-eaa1-48ee-b59f-9edc56659f4b)

But it's not a big issue in day to day usage

**Comment by n7itro** [comment]
> @n7itro I've also encountered this bug when bookmark toolbar is disabled
> 
> ![image](https://private-user-images.githubusercontent.com/113062544/359610716-58294d0d-6641-4f6d-835d-af2b9c8e344a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxODEyOTQsIm5iZiI6MTcyNDE4MDk5NCwicGF0aCI6Ii8xMTMwNjI1NDQvMzU5NjEwNzE2LTU4Mjk0ZDBkLTY2NDEtNGY2ZC04MzVkLWFmMmI5YzhlMzQ0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxOTA5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDA0NWIxNzViNTVmYjc0NzFkMzZmMTU3NTJkZjllMTA1ODQ4NjdiNWJhMjg0MWQwMzA2YzgxNTlhMDU3MjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jCkIU3J9qQC8zBcdMlU-R3QX3m1jIpy0LmObp327wys)

This is why I added "only works with bookmarks toolbar enabled" to the theme readme

> and browser needs to be restarted to use bookmark toolbar after enabling it otherwise it hides too early
> Screencast.from.2024-08-20.21-04-54.webm
> 

This is what i meant by animation not working,


I'll see what I can do about these three bugs. Thanks!

**Comment by damian-ds7** [comment]
> This is why I added "only works with bookmarks toolbar enabled" to the theme readme

oh right I missed that

> I'll see what I can do about these three bugs. Thanks

Thanks again for adding this function, I got really used to it and now I can fully switch to zen

**Comment by n7itro** [comment]
I resolved most of the issues. Be sure to reinstall the theme to get the update 😃
