### ISSUE TITLE
When this is enabled, it's not possible to close the last tab/window

### ISSUE THREAD

**Issue by MathewBlanc** [n7itro/Zen-Themes#11]
Let me know if there's more info you need

# Steps to reproduce

1. Open a window
2. Close down to only have a 'new tab' page open
3. Try to close the window with cmd+w 

When I do this, it just opens a new tab again. I had to go in and disable the theme and close the window using the buttons, then re-enable the theme. 

# Device
Macbook Air M1

**Comment by n7itro** [comment]
You can enable `browser.tabs.closeWindowWithLastTab` in `about:config`
