### ISSUE TITLE
Not doing anything

### ISSUE THREAD

**Issue by Hungermanw3t** [n7itro/Zen-Themes#12]
when i install the mod it actually fixes github favicons but does nothing else.
Before:
![image](https://github.com/user-attachments/assets/6b068468-f57e-4a30-b7eb-470df709cc86)

After:
![image](https://github.com/user-attachments/assets/4aecf405-494f-4008-8ee3-0451c91690ed)

**Comment by n7itro** [comment]
The mod still works for me... Make sure to check the options in the Zen Mod settings (`about:preferences#zenMarketplace`)
