### ISSUE TITLE
Spacing issue in UI

### ISSUE THREAD

**Issue by MUTLCC** [n7itro/Zen-Themes#19]
![resim](https://github.com/user-attachments/assets/407ef90d-d312-4324-b753-a63984801b6e)

Hello firstly I love your mod and I am grateful to you for creating it.

As you can see in the image, there is a space issue between the toolbar and the bookmarks bar in the UI in this way.
Can you solve this problem?

**Comment by MUTLCC** [comment]
I solved this problem by replacing the ‘-5px’ value in the ‘margin-bottom: calc(-5px - var(--urlbar-min-height));’ section in the ‘chrome.css’ file with ‘0px’. If there is no more permanent and proper solution, you can fix it by accepting my pull request.

**Comment by antikovt** [comment]
Here to +1 and add that the urlbar seems to be off even with the bookmarks collapsed. The whole top bar becomes shorter when you enable the bookmarks bar with the extension enabled.

![image](https://github.com/user-attachments/assets/73eec6fa-cb8e-46e2-8913-85039767eaab)
Bookmarks disabled

![image](https://github.com/user-attachments/assets/ea0fea70-fa5d-4bda-9add-9bd5e3736dcf)
Bookmarks enabled (Ctrl+Shift+B)
