### ISSUE TITLE
it should be run after install 

### ISSUE THREAD

**Issue by albu-ali** [n7itro/Zen-Themes#2]
Hey and thinks for nice theme 

I hope if you just make the theme enable after install so the user don't think that the theme is broken or it's don't working 

Edit: I know how to enable the theme from the Look and Feel > Theme Settings > Hide Window Buttons 
but other may not know that and think that theme is broken

**Comment by n7itro** [comment]
Every theme includes the following
> Each of these settings can be enabled individually by changing the configuration in the settings page.

Since my themes have multiple settings, there is no default

**Comment by rubaboo** [comment]
I had the same momentary confusion upon installing Hide Window Buttons. I agree it would be less confusing if the buttons were hidden immediately upon installing the mod. To be clear, I am not suggesting to remove the settings, I just think they should be in the enabled state to begin with. Cheers.
