### ISSUE TITLE
Is it possible to show bookmarks only when i open a new tab?

### ISSUE THREAD

**Issue by Ozzornin** [n7itro/Zen-Themes#21]
I like the way Mozilla works with the bookmarks toolbar. It only appears when I open a new tab. 
I'm used to the fact that when I open a bookmark, it opens in a new tab.
Is there a way to make bookmarks open in a new tab, or to make the bookmarks toolbar show up when I open a new tab?

**Comment by n7itro** [comment]
Enable `browser.tabs.loadBookmarksInTabs` in about:config
