### ISSUE TITLE
Too much padding when enabling "Expand the bookmarks toolbar by hovering"

### ISSUE THREAD

**Issue by Impasse52** [n7itro/Zen-Themes#23]
Enabling "Expand the bookmarks toolbar by hovering" in Bookmark Toolbar Tweaks causes extra padding to appear even when the bookmark toolbar is hidden. 

This is how it looks with the bookmarks toolbar disabled:

![image](https://github.com/user-attachments/assets/8dad2a64-2c37-4631-a448-2f2b63137dd1)

and this is how it looks like when the toolbar is enabled:
![image](https://github.com/user-attachments/assets/83541e3b-84d6-4464-ad16-4898ef32936f)

I would love this feature if the padding was as in the first screenshot while still being able to hover to show bookmarks. As it is now, it looks very chunky and asymmetrical, which kind of defeats the purpose of having such a feature, personally.

**Comment by damian-ds7** [comment]
I tried fixing it but it caused issues for others. You can try editing the mod css file to fix it on your device.

```
    @media (-moz-bool-pref: "uc.bookmarks.expand-on-search") or (-moz-bool-pref: "uc.bookmarks.expand-on-hover") {
        #PersonalToolbar[collapsed="false"]:not([customizing]) {
            position: relative;
            margin-bottom: calc(0px - var(--urlbar-min-height));
            transform: rotateX(90deg) !important;
            transform-origin: top;
            transition: transform 135ms linear !important;
            z-index: 1;
        }
    }
```
change the 0px to whatever works for you in margin-bottom. IIRC this mods files are in chrome/zen-themes/ea1a.../

**Comment by Impasse52** [comment]
> I tried fixing it but it caused issues for others. You can try editing the mod css file to fix it on your device.
> 
> ```
>     @media (-moz-bool-pref: "uc.bookmarks.expand-on-search") or (-moz-bool-pref: "uc.bookmarks.expand-on-hover") {
>         #PersonalToolbar[collapsed="false"]:not([customizing]) {
>             position: relative;
>             margin-bottom: calc(0px - var(--urlbar-min-height));
>             transform: rotateX(90deg) !important;
>             transform-origin: top;
>             transition: transform 135ms linear !important;
>             z-index: 1;
>         }
>     }
> ```
> 
> change the 0px to whatever works for you in margin-bottom. IIRC this mods files are in chrome/zen-themes/ea1a.../

Thank you, this seems to do the trick! What kind of issues does this cause? Just so I know what to look out for.

**Comment by damian-ds7** [comment]
If it works for you than I don't think you have to worry. It's just that the value you set can not work well everywhere and there was a [padding issue](#19) with my changes some time ago.
