### ISSUE TITLE
Spacing broken again after last update :(

### ISSUE THREAD

**Issue by antikovt** [n7itro/Zen-Themes#24]
The latest Zen update moved the spacings around the url bar, causing a conflict with the extension. #19 Needs to be rolled back maybe. The url bar now goes outside of the appropriate space when the extension is enabled.

![image](https://github.com/user-attachments/assets/c6e2bc01-b1a0-45af-a9eb-668a21274662)
Bookmarks+extension enabled

![image](https://github.com/user-attachments/assets/2ed55a22-a3d0-4871-be42-468ff7eec356)
Bookmarks disabled

**Comment by hlytus** [comment]
Update the browser again. It should be fixed
