### ISSUE TITLE
Suggestion: Add background to bookmark toolbar on "expand to hover"

### ISSUE THREAD

**Issue by BosadBillaHun** [n7itro/Zen-Themes#5]
When the "Expand to hover" is checked, the bookmarks toolbar has a transparent background.
Can you add 2 more features that lets the user to:
1. add background to it
2. change the opacity of the background

**Comment by n7itro** [comment]
Solved with zen-browser/theme-store#165 

I will let you know when the update gets approved by the Zen developer.

**Comment by BosadBillaHun** [comment]
Okay
