### ISSUE TITLE
Left elements not reachable if window in narrow

### ISSUE THREAD

**Issue by SHU-red** [n7itro/Zen-Themes#9]
If the browser window is very narrow, there is the (usual) error, giving the opportunity to see the bookmarks on the far right side via dropdown

Since this add-on changes the behavior, the elements to the far right can not be acessed because there is no arrow for creating a dropdown for the left elements out of sight

solution:
As soon as the windows with is smaller than the width of the bookmarks toolbar, the toolbar shall behave like the standard left-sided alignment

**Comment by n7itro** [comment]
The drop-down button is still visible for me with the bookmarks centered...
Also, I'm not sure whether this logic is possible in pure CSS
